import { strict as assert } from "node:assert";
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve as resolvePath } from "node:path";
import { test } from "node:test";

const SCRIPT_PATH = resolvePath(
  new URL("../scripts/migrate-manifests-v10.mjs", import.meta.url).pathname,
);

function tempDir() {
  return mkdtempSync(join(tmpdir(), "agent-runner-migrate-v10-"));
}

function writeManifest(root, repo, runId, manifest) {
  const dir = join(root, "runs", repo, runId);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "run.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  return join(dir, "run.json");
}

function readManifest(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function directLauncher() {
  return { kind: "direct", name: "direct" };
}

test("migrate-manifests-v10 script dry-runs promotions/repairs and reports canonical v10 no-ops", () => {
  const root = tempDir();
  const v9Path = writeManifest(root, "demo", "run-v9", {
    schemaVersion: 9,
    runId: "run-v9",
    backend: "claude",
    model: null,
    effort: null,
    cwd: "/repo",
    message: null,
    name: null,
    note: null,
    pinned: false,
    unrestricted: false,
    timeoutSec: 10,
    maxAttempts: 4,
    brief: "brief",
    runtimeVars: {},
    lockedFields: [],
    dependencyRunIds: [],
    attachments: [],
    finalTasks: {},
    resetSeed: {
      backend: "claude",
      model: null,
      effort: null,
      cwd: "/repo",
      lockedFields: [],
      message: null,
      name: null,
      note: null,
      pinned: false,
      dependencyRunIds: [],
      unrestricted: false,
      timeoutSec: 10,
      maxAttempts: 4,
      brief: "brief",
      runtimeVars: {},
      hookState: {},
      attachments: [],
      finalTasks: {},
    },
  });
  const v10RepairPath = writeManifest(root, "demo", "run-v10-repair", {
    schemaVersion: 10,
    runId: "run-v10-repair",
    backend: "claude",
    model: null,
    effort: null,
    cwd: "/repo",
    message: null,
    name: null,
    unrestricted: false,
    timeoutSec: 10,
    maxAttempts: 4,
    brief: "brief",
    runtimeVars: {},
    lockedFields: [],
    dependencyRunIds: [],
    attachments: [],
    finalTasks: {},
    resetSeed: {
      backend: "claude",
      model: null,
      effort: null,
      cwd: "/repo",
      lockedFields: [],
      message: null,
      name: null,
      dependencyRunIds: [],
      unrestricted: false,
      timeoutSec: 10,
      maxAttempts: 4,
      brief: "brief",
      runtimeVars: {},
      hookState: {},
      attachments: [],
      finalTasks: {},
    },
  });
  writeManifest(root, "demo", "run-v10", {
    schemaVersion: 10,
    runId: "run-v10",
    backend: "claude",
    model: null,
    effort: null,
    cwd: "/repo",
    message: null,
    name: null,
    note: null,
    pinned: false,
    unrestricted: false,
    timeoutSec: 10,
    maxAttempts: 4,
    brief: "brief",
    runtimeVars: {},
    lockedFields: [],
    dependencyRunIds: [],
    attachments: [],
    finalTasks: {},
    archivedAt: null,
    launcher: directLauncher(),
    callerInstructions: null,
    resetSeed: {
      backend: "claude",
      model: null,
      effort: null,
      launcher: directLauncher(),
      cwd: "/repo",
      lockedFields: [],
      message: null,
      name: null,
      note: null,
      pinned: false,
      dependencyRunIds: [],
      unrestricted: false,
      timeoutSec: 10,
      maxAttempts: 4,
      brief: "brief",
      runtimeVars: {},
      hookState: {},
      attachments: [],
      finalTasks: {},
    },
  });

  const stdout = execFileSync("node", [SCRIPT_PATH, "--root", root], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });

  assert.match(stdout, /DRY\s+.*run-v9\/run\.json: would promote to schemaVersion 10/);
  assert.match(
    stdout,
    /DRY\s+.*run-v10-repair\/run\.json: would canonicalize schemaVersion 10 state/,
  );
  assert.match(stdout, /OK\s+.*run-v10\/run\.json: already canonical schemaVersion 10 state/);
  assert.equal(readManifest(v9Path).schemaVersion, 9);
  assert.equal(readManifest(v10RepairPath).schemaVersion, 10);
});

test("migrate-manifests-v10 script writes v9 launcher and caller-instructions upgrades", () => {
  const root = tempDir();
  const v9Path = writeManifest(root, "demo", "run-v9", {
    schemaVersion: 9,
    runId: "run-v9",
    backend: "claude",
    model: null,
    effort: null,
    cwd: "/repo",
    message: null,
    name: null,
    note: null,
    pinned: false,
    unrestricted: false,
    timeoutSec: 10,
    maxAttempts: 4,
    brief: "brief",
    runtimeVars: {},
    lockedFields: [],
    dependencyRunIds: [],
    attachments: [],
    finalTasks: {},
    resetSeed: {
      backend: "claude",
      model: null,
      effort: null,
      cwd: "/repo",
      lockedFields: [],
      message: null,
      name: null,
      note: null,
      pinned: false,
      dependencyRunIds: [],
      unrestricted: false,
      timeoutSec: 10,
      maxAttempts: 4,
      brief: "brief",
      runtimeVars: {},
      hookState: {},
      attachments: [],
      finalTasks: {},
    },
  });
  const validV10Path = writeManifest(root, "demo", "run-v10", {
    schemaVersion: 10,
    runId: "run-v10",
    backend: "claude",
    model: null,
    effort: null,
    cwd: "/repo",
    message: null,
    name: null,
    note: null,
    pinned: false,
    unrestricted: false,
    timeoutSec: 10,
    maxAttempts: 4,
    brief: "brief",
    runtimeVars: {},
    lockedFields: [],
    dependencyRunIds: [],
    attachments: [],
    finalTasks: {},
    archivedAt: null,
    launcher: directLauncher(),
    callerInstructions: null,
    resetSeed: {
      backend: "claude",
      model: null,
      effort: null,
      launcher: directLauncher(),
      cwd: "/repo",
      lockedFields: [],
      message: null,
      name: null,
      note: null,
      pinned: false,
      dependencyRunIds: [],
      unrestricted: false,
      timeoutSec: 10,
      maxAttempts: 4,
      brief: "brief",
      runtimeVars: {},
      hookState: {},
      attachments: [],
      finalTasks: {},
    },
  });

  const writeRun = execFileSync("node", [SCRIPT_PATH, "--root", root, "--write"], {
    encoding: "utf8",
  });

  assert.match(writeRun, /WRITE\s+.*run-v9\/run\.json: promoted to schemaVersion 10/);
  assert.match(writeRun, /OK\s+.*run-v10\/run\.json: already canonical schemaVersion 10 state/);
  assert.deepEqual(readManifest(v9Path), {
    schemaVersion: 10,
    runId: "run-v9",
    backend: "claude",
    model: null,
    effort: null,
    cwd: "/repo",
    message: null,
    name: null,
    note: null,
    pinned: false,
    unrestricted: false,
    timeoutSec: 10,
    maxAttempts: 4,
    brief: "brief",
    runtimeVars: {},
    lockedFields: [],
    dependencyRunIds: [],
    attachments: [],
    finalTasks: {},
    archivedAt: null,
    launcher: directLauncher(),
    callerInstructions: null,
    resetSeed: {
      backend: "claude",
      model: null,
      effort: null,
      launcher: directLauncher(),
      cwd: "/repo",
      lockedFields: [],
      message: null,
      name: null,
      note: null,
      pinned: false,
      dependencyRunIds: [],
      unrestricted: false,
      timeoutSec: 10,
      maxAttempts: 4,
      brief: "brief",
      runtimeVars: {},
      hookState: {},
      attachments: [],
      finalTasks: {},
    },
  });
  assert.deepEqual(readManifest(validV10Path), {
    schemaVersion: 10,
    runId: "run-v10",
    backend: "claude",
    model: null,
    effort: null,
    cwd: "/repo",
    message: null,
    name: null,
    note: null,
    pinned: false,
    unrestricted: false,
    timeoutSec: 10,
    maxAttempts: 4,
    brief: "brief",
    runtimeVars: {},
    lockedFields: [],
    dependencyRunIds: [],
    attachments: [],
    finalTasks: {},
    archivedAt: null,
    launcher: directLauncher(),
    callerInstructions: null,
    resetSeed: {
      backend: "claude",
      model: null,
      effort: null,
      launcher: directLauncher(),
      cwd: "/repo",
      lockedFields: [],
      message: null,
      name: null,
      note: null,
      pinned: false,
      dependencyRunIds: [],
      unrestricted: false,
      timeoutSec: 10,
      maxAttempts: 4,
      brief: "brief",
      runtimeVars: {},
      hookState: {},
      attachments: [],
      finalTasks: {},
    },
  });
});

test("migrate-manifests-v10 script filters to selected repo buckets", () => {
  const root = tempDir();
  const agentRunnerPath = writeManifest(root, "agent-runner", "run-agent-runner", {
    schemaVersion: 9,
    runId: "run-agent-runner",
    backend: "claude",
    model: null,
    effort: null,
    cwd: "/repo",
    message: null,
    name: null,
    note: null,
    pinned: false,
    unrestricted: false,
    timeoutSec: 10,
    maxAttempts: 4,
    brief: "brief",
    runtimeVars: {},
    lockedFields: [],
    dependencyRunIds: [],
    attachments: [],
    finalTasks: {},
    resetSeed: {
      backend: "claude",
      model: null,
      effort: null,
      cwd: "/repo",
      lockedFields: [],
      message: null,
      name: null,
      note: null,
      pinned: false,
      dependencyRunIds: [],
      unrestricted: false,
      timeoutSec: 10,
      maxAttempts: 4,
      brief: "brief",
      runtimeVars: {},
      hookState: {},
      attachments: [],
      finalTasks: {},
    },
  });
  const assistantPath = writeManifest(root, "assistant", "run-assistant", {
    schemaVersion: 9,
    runId: "run-assistant",
    backend: "claude",
    model: null,
    effort: null,
    cwd: "/repo",
    message: null,
    name: null,
    note: null,
    pinned: false,
    unrestricted: false,
    timeoutSec: 10,
    maxAttempts: 4,
    brief: "brief",
    runtimeVars: {},
    lockedFields: [],
    dependencyRunIds: [],
    attachments: [],
    finalTasks: {},
    resetSeed: {
      backend: "claude",
      model: null,
      effort: null,
      cwd: "/repo",
      lockedFields: [],
      message: null,
      name: null,
      note: null,
      pinned: false,
      dependencyRunIds: [],
      unrestricted: false,
      timeoutSec: 10,
      maxAttempts: 4,
      brief: "brief",
      runtimeVars: {},
      hookState: {},
      attachments: [],
      finalTasks: {},
    },
  });

  const writeRun = execFileSync(
    "node",
    [SCRIPT_PATH, "--root", root, "--repo", "agent-runner", "--write"],
    {
      encoding: "utf8",
    },
  );

  assert.match(writeRun, /WRITE\s+.*run-agent-runner\/run\.json: promoted to schemaVersion 10/);
  assert.match(writeRun, /SKIP\s+.*run-assistant\/run\.json: repo bucket assistant not selected/);
  assert.deepEqual(readManifest(agentRunnerPath), {
    schemaVersion: 10,
    runId: "run-agent-runner",
    backend: "claude",
    model: null,
    effort: null,
    cwd: "/repo",
    message: null,
    name: null,
    note: null,
    pinned: false,
    unrestricted: false,
    timeoutSec: 10,
    maxAttempts: 4,
    brief: "brief",
    runtimeVars: {},
    lockedFields: [],
    dependencyRunIds: [],
    attachments: [],
    finalTasks: {},
    archivedAt: null,
    launcher: directLauncher(),
    callerInstructions: null,
    resetSeed: {
      backend: "claude",
      model: null,
      effort: null,
      launcher: directLauncher(),
      cwd: "/repo",
      lockedFields: [],
      message: null,
      name: null,
      note: null,
      pinned: false,
      dependencyRunIds: [],
      unrestricted: false,
      timeoutSec: 10,
      maxAttempts: 4,
      brief: "brief",
      runtimeVars: {},
      hookState: {},
      attachments: [],
      finalTasks: {},
    },
  });
  assert.deepEqual(readManifest(assistantPath), {
    schemaVersion: 9,
    runId: "run-assistant",
    backend: "claude",
    model: null,
    effort: null,
    cwd: "/repo",
    message: null,
    name: null,
    note: null,
    pinned: false,
    unrestricted: false,
    timeoutSec: 10,
    maxAttempts: 4,
    brief: "brief",
    runtimeVars: {},
    lockedFields: [],
    dependencyRunIds: [],
    attachments: [],
    finalTasks: {},
    resetSeed: {
      backend: "claude",
      model: null,
      effort: null,
      cwd: "/repo",
      lockedFields: [],
      message: null,
      name: null,
      note: null,
      pinned: false,
      dependencyRunIds: [],
      unrestricted: false,
      timeoutSec: 10,
      maxAttempts: 4,
      brief: "brief",
      runtimeVars: {},
      hookState: {},
      attachments: [],
      finalTasks: {},
    },
  });
});
